### ISSUE TITLE
Feature request: Upload files

### ISSUE THREAD

**Issue by malaow3** [ielm/utapi-rs#2]
Was wondering if adding the API routes for uploading files is planned for this project? I was taking a look to see if I could port over the TS/JS implementation, but my general working knowledge of TS/JS is a bit lacking for me to make any meaningful progress in the short time frame I was testing things out. Would be happy to help out with getting this feature in though!

**Comment by ielm** [comment]
Absolutely, I'm in a work crunch at the moment so might be a little slow but let me put together a plan and I'll add it to this thread! Thanks for your help on this @malaow3

**Comment by malaow3** [comment]
I actually was able to make some headway on file uploads! Not a complete 1:1 of the JS/TS implementation but it's a decent start AND selfishly is good enough for my use case. I will clean up the code and put up a PR soon. Thanks for laying the groundwork with this package!
